<a href="https://colab.research.google.com/github/pranaviii04/Machine-Learning-Labs/blob/main/NumPy_Master_Guided_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧑‍💻 NumPy Complete Guided Project
**Instructor / Student Colab Notebook** – covers *all* key concepts from `Numpy‑1` to `Numpy‑5`.

*Generated: 08 Aug 2025*


**Table of Contents**

1. [Setup](#setup)  
2. [Array Creation & Dtypes](#creation)  
3. [Array Attributes & Inspection](#attributes)  
4. [Indexing, Slicing, Fancy Indexing](#indexing)  
5. [Reshaping, Transpose & Copies vs Views](#reshape)  
6. [Joining, Splitting, Set & Sorting Ops](#join)  
7. [Arithmetic Ops, Universal Functions](#arithmetic)  
8. [Broadcasting (Rules + Examples)](#broadcast)  
9. [Statistics & Aggregations](#stats)  
10. [Random Numbers & Reproducibility](#random)  
11. [Structured / Recarrays](#structured)  
12. [Linear Algebra Essentials](#linalg)  
13. [File I/O (`npy`, `npz`, `txt`)](#io)  
14. [Datetime64 & Timedelta64](#datetime)  
15. [Masked Arrays & NaNs](#mask)  
16. [Mini‑Project — Fitness Data Analysis](#project)  
17. [Conclusion & Next Steps](#conclusion)  


## <a name='setup'></a>1️⃣ Setup

In [8]:
import numpy as np, math, os, pathlib, types, textwrap, random
print('NumPy version:', np.__version__)

NumPy version: 2.0.2


## <a name='creation'></a>2️⃣ Array Creation & Dtypes

Key functions: `np.array`, `np.arange`, `np.linspace`, `zeros`, `ones`, `full`, `eye`, `identity`, `diag`, `empty`

In [ ]:
# EXAMPLE
arr1 = np.array([1, 2, 3], dtype=np.int32)
arr2 = np.linspace(0, 1, 6)
arr3 = np.full((2,3), 7.5)
print(arr1, arr2, arr3, sep="\n")
print("dtypes:", arr1.dtype, arr2.dtype)


In [ ]:
# 🖊️ TODO: create a 10×10 chessboard pattern using zeros & ones
import numpy as np

chessboard=np.full((10,10),0)
chessboard[1::2, ::2] = 1
chessboard[::2, 1::2] = 1
print(chessboard)


[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


## <a name='attributes'></a>3️⃣ Array Attributes & Inspection

`shape`, `ndim`, `size`, `dtype`, `itemsize`, `nbytes`

In [ ]:
M = np.arange(12).reshape(3,4)
print('shape', M.shape, 'ndim', M.ndim, 'size', M.size, 'itemsize', M.itemsize, 'total bytes', M.nbytes)


In [4]:
# 🖊️ TODO: check memory footprint of a 1000×1000 float64 array
arr=np.arange(1000*1000, dtype=np.float64 )
print(arr.nbytes)

8000000


## <a name='indexing'></a>4️⃣ Indexing, Slicing & Fancy Indexing

In [5]:
a = np.arange(1,26).reshape(5,5)
print(a[:, 0])     # first column
print(a[::2, ::2]) # every 2nd row/col
mask = (a % 3 == 0)
print('multiples of 3:', a[mask])


[ 1  6 11 16 21]
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
multiples of 3: [ 3  6  9 12 15 18 21 24]


In [7]:
# 🖊️ TODO: use fancy indexing to swap first and last rows of `a`
a = np.arange(1,26).reshape(5,5)
a[[0,-1]]=a[[-1,0]]
print(a)

[[21 22 23 24 25]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 1  2  3  4  5]]


## <a name='reshape'></a>5️⃣ Reshaping, Transpose & Copies vs Views

In [9]:
b = np.arange(8)
B = b.reshape(2,4)
B[0,0] = 99
print('b is modified:', b)
C = b.reshape(2,4).copy()
C[0,0] = -1
print('b unchanged with copy:', b)


b is modified: [99  1  2  3  4  5  6  7]
b unchanged with copy: [99  1  2  3  4  5  6  7]


In [15]:
# 🖊️ TODO: Flatten a 3‑D array into 1‑D using both `ravel` and `flatten`; observe copy vs view.
A = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
              [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]])

flat = A.flatten()
print("flattened array:", flat)
rav = A.ravel()
print("raveled array:", rav)

flat[0] = -1
print("original array after modifying flattened:\n", A)
print("Flatten array after modifying",flat)

rav[0] = 999
print("original array after modifying raveled:\n", A)
print("Raveled array after modifying",rav)

flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12  1  2  3  4  5  6  7  8  9 10 11 12]
raveled array: [ 1  2  3  4  5  6  7  8  9 10 11 12  1  2  3  4  5  6  7  8  9 10 11 12]
original array after modifying flattened:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Flatten array after modifying [-1  2  3  4  5  6  7  8  9 10 11 12  1  2  3  4  5  6  7  8  9 10 11 12]
original array after modifying raveled:
 [[[999   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]]

 [[  1   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]]]
Raveled array after modifying [999   2   3   4   5   6   7   8   9  10  11  12   1   2   3   4   5   6
   7   8   9  10  11  12]


## <a name='join'></a>6️⃣ Joining, Splitting, Set & Sorting Ops

In [16]:
x = np.array([1,3,5]); y = np.array([2,4,6])
xy = np.concatenate([x,y])
print('union', np.union1d(x,y))
print('intersect', np.intersect1d(xy,[1,2,10]))
print('sorted descending', np.sort(xy)[::-1])


union [1 2 3 4 5 6]
intersect [1 2]
sorted descending [6 5 4 3 2 1]


In [23]:
# 🖊️ TODO: split `xy` back into two equal halves using `np.array_split`
x = np.array([1,3,5]); y = np.array([2,4,6])
xy = np.concatenate([x,y])
print(np.split(xy,2))

[array([1, 3, 5]), array([2, 4, 6])]


## <a name='arithmetic'></a>7️⃣ Arithmetic Ops & Universal Functions

In [ ]:
v = np.arange(5)
print('exp', np.exp(v))
print('sin', np.sin(v))
print('vectorised addition', v + 10)


In [2]:
# 🖊️ TODO: given degrees [0,30,45,60,90], compute radians and sin values.
import numpy as np

v=np.array([0,30,45,60,90])
rad=np.radians(v)
sine=np.sin(rad)

print(rad)
print(sine)

[0.         0.52359878 0.78539816 1.04719755 1.57079633]
[0.         0.5        0.70710678 0.8660254  1.        ]


## <a name='broadcast'></a>8️⃣ Broadcasting Rules

Rules: compare dimensions from right → left; stretch size 1 dims; mismatch error.

In [ ]:
row = np.arange(5)
col = np.arange(3).reshape(3,1)
matrix = row + col  # broadcast to 3×5
print(matrix)


In [3]:
# 🖊️ TODO: use broadcasting to create a 10×10 multiplication table.
import numpy as np

row=np.arange(1,11).reshape(1,10)
col=np.arange(1,11).reshape(10,1)
table=row*col
print(table)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


## <a name='stats'></a>9️⃣ Statistics & Aggregations

In [ ]:
data = np.random.default_rng(0).integers(1, 100, size=(5,4))
print('data\n', data)
print('row sums', data.sum(axis=1))
print('col means', data.mean(axis=0))


In [5]:
# 🖊️ TODO: compute `np.percentile` (25th, 50th, 75th) of flattened `data`.
import numpy as np

data = np.random.default_rng(0).integers(1, 100, size=(5,4))
percentiles = np.percentile(data.flatten(), [25, 50, 75])

# Print the results
print("25th percentile:", percentiles[0])
print("50th percentile (median):", percentiles[1])
print("75th percentile:", percentiles[2])

25th percentile: 30.0
50th percentile (median): 58.5
75th percentile: 75.0


## <a name='random'></a>🔟 Random Numbers & Reproducibility

In [ ]:
rng = np.random.default_rng(42)
rand_floats = rng.random(5)
rand_ints = rng.integers(low=10, high=50, size=5)
print(rand_floats, rand_ints)
rng2 = np.random.default_rng(42)
assert np.allclose(rand_floats, rng2.random(5))


In [6]:
# 🖊️ TODO: simulate rolling a fair six‑sided die 100 times; estimate proportion of 6s.
import numpy as np

rolls = np.random.randint(1, 7, size=100)

proportion_of_sixes = np.sum(rolls == 6) / len(rolls)

print("Proportion of 6s:", proportion_of_sixes)


Proportion of 6s: 0.25


## <a name='structured'></a>1️⃣1️⃣ Structured / Record Arrays

In [ ]:
people = np.array([('Alice', 25, 55.0), ('Bob', 30, 85.5)],
                   dtype=[('name','U10'), ('age','i4'), ('weight','f4')])
print(people['name'], people['age'].mean())


In [8]:
# 🖊️ TODO: add a new field 'height' to the structured array using `np.lib.recfunctions.append_fields` (hint: pip install?).
import numpy as np
from numpy.lib import recfunctions as rfn

people = np.array([
    ('Alice', 25, 55.0),
    ('Bob', 30, 85.5)
], dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

height_data = [165.0, 180.0]
people_with_height = rfn.append_fields(people, 'height', height_data, dtypes='f4', usemask=False)
print(people_with_height)


[('Alice', 25, 55. , 165.) ('Bob', 30, 85.5, 180.)]


## <a name='linalg'></a>1️⃣2️⃣ Linear Algebra Essentials

In [ ]:
A = np.random.random((3,3))
b = np.random.random(3)
x = np.linalg.solve(A, b)
print('A·x ≈ b?', np.allclose(A.dot(x), b))


In [9]:
# 🖊️ TODO: compute eigenvalues of `A` using `np.linalg.eig`.
import numpy as np

A = np.array([[4, 2],
              [1, 3]])

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


## <a name='io'></a>1️⃣3️⃣ File I/O (`npy`, `npz`, `txt`)

In [ ]:
np.save('array.npy', A)
loaded = np.load('array.npy')
print('loaded equals A?', np.allclose(loaded, A))
np.savez('multi_arrays.npz', A=A, b=b)


In [10]:
# 🖊️ TODO: Use `np.savetxt` to write `data` (from stats section) to CSV then reload with `np.loadtxt`.
import numpy as np

data = np.random.randint(0, 100, size=(5, 3))

np.savetxt('data.csv', data, delimiter=',', fmt='%d')
loaded_data = np.loadtxt('data.csv', delimiter=',')

print("Original Data:\n", data)
print("\nReloaded Data:\n", loaded_data)


Original Data:
 [[11 31  2]
 [34 86 52]
 [69 28 95]
 [92 87 11]
 [28 47 92]]

Reloaded Data:
 [[11. 31.  2.]
 [34. 86. 52.]
 [69. 28. 95.]
 [92. 87. 11.]
 [28. 47. 92.]]


## <a name='datetime'></a>1️⃣4️⃣ Datetime64 & Timedelta64

In [ ]:
dates = np.arange('2023-01', '2023-04', dtype='datetime64[D]')
delta = dates[1:] - dates[:-1]
print(dates[:5], delta[0])


In [11]:
# 🖊️ TODO: find how many Mondays appear in `dates` array.
import numpy as np

dates = np.arange('2023-01', '2023-04', dtype='datetime64[D]')
weekdays = dates.astype('datetime64[D]').astype('int') % 7
num_mondays = np.sum(weekdays == 0)

print(f"Number of Mondays: {num_mondays}")


Number of Mondays: 13


## <a name='mask'></a>1️⃣5️⃣ Masked Arrays & NaNs

In [ ]:
arr = np.array([1, 2, np.nan, 4, np.nan])
masked = np.ma.masked_invalid(arr)
print(masked.mean())


In [12]:
# 🖊️ TODO: replace NaNs with column means in a 2‑D array containing NaNs.
import numpy as np

arr = np.array([[1, 2, np.nan],
                [4, np.nan, 6],
                [7, 8, 9]])
col_means = np.nanmean(arr, axis=0)
inds = np.where(np.isnan(arr))

arr[inds] = np.take(col_means, inds[1])

print("Array after replacing NaNs with column means:")
print(arr)


Array after replacing NaNs with column means:
[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


## <a name='project'></a>1️⃣6️⃣ Mini‑Project: Fitness Data Analysis

In [ ]:
fitness = np.genfromtxt('fitness.txt', delimiter='\t', dtype=None, encoding=None, names=True)
print('columns:', fitness.dtype.names, 'rows:', len(fitness))


In [16]:
import numpy as np
from numpy.lib import recfunctions as rfn

people = np.array([('Alice', 25, 55.0), ('Bob', 30, 85.5)],
                  dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

height = np.array([165.0, 180.0], dtype='f4')
people = rfn.append_fields(people, 'height', height, usemask=False)

bmi = people['weight'] / ((people['height'] / 100) ** 2)
people = rfn.append_fields(people, 'fitness', bmi, usemask=False)

print(people)


[('Alice', 25, 55. , 165., 20.20202 ) ('Bob', 30, 85.5, 180., 26.388891)]


## <a name='conclusion'></a>1️⃣7️⃣ Conclusion & Further Practice
Congrats on covering **all core NumPy topics** from your five lecture notebooks!

*Keep experimenting, read the official docs, and try converting your NumPy pipelines into Pandas or JAX for more fun.*